DROP DATABASE DBFLORICAR;
CREATE DATABASE DBFLORICAR;

USE DBFLORICAR;

CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(100),
    SOBRENOME VARCHAR(100),
    CPF CHAR(11),
    EMAIL VARCHAR(100),
    CNH INT,
	CONTATO VARCHAR(20),
    ENDERECO VARCHAR(100),
	CIDADE VARCHAR(45),
    ESTADO CHAR(2),
    CEP CHAR(8)
);

CREATE TABLE VEICULO (
	IDVEICULO INT NOT NULL PRIMARY KEY,
    PLACA VARCHAR(100),
    RENAVAM INT,
    CHASSI VARCHAR(100),
    MARCA VARCHAR(100),
    MODELO VARCHAR(100),
    ANO INT,
    COR VARCHAR(100),
    MOTOR VARCHAR(100),
    TRANSMISSAO VARCHAR(100)
);

CREATE TABLE LOCACAO (
	IDLOCACAO INT NOT NULL PRIMARY KEY,
    IDCLIENTE INT NOT NULL,
    IDVEICULO INT NOT NULL,
    DTLOCACAO DATETIME,
    KMLOCACAO INT,
    DTENTREGA DATETIME,
    KMENTREGA INT,
    FOREIGN KEY(IDCLIENTE)
		REFERENCES CLIENTE (IDCLIENTE),
	FOREIGN KEY(IDVEICULO) 
		REFERENCES VEICULO (IDVEICULO)
);

SELECT * FROM CLIENTE;
SELECT * FROM VEICULO;
SELECT * FROM LOCACAO;