DROP DATABASE DBFLORICAR;
CREATE DATABASE DBFLORICAR;

USE DBFLORICAR;

CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100),
    SOBRENOME VARCHAR(100),
    CPF VARCHAR(20),
    EMAIL VARCHAR(100),
    CNH VARCHAR(20),
	TELEFONE VARCHAR(20),
    ENDERECO VARCHAR(100),
	CIDADE VARCHAR(45),
    ESTADO CHAR(2),
    CEP VARCHAR(10),
    PRIMARY KEY(IDCLIENTE)
);

CREATE TABLE VEICULO (
	IDVEICULO INT NOT NULL AUTO_INCREMENT, 
    PLACA VARCHAR(100),
    RENAVAM VARCHAR(50),
    CHASSI VARCHAR(100),
    MARCA VARCHAR(100),
    MODELO VARCHAR(100),
    ANO INT,
    COR VARCHAR(100),
    MOTOR INT,
    TRANSMISSAO VARCHAR(100),
    PRIMARY KEY(IDVEICULO)
);

CREATE TABLE LOCACAO (
	IDLOCACAO INT NOT NULL AUTO_INCREMENT ,
    DATA_LOCACAO DATE,
    KMLOCACAO DOUBLE,
    DATA_ENTREGA DATE,
    KMENTREGA DOUBLE,
    IDCLIENTE INT NOT NULL,
    IDVEICULO INT NOT NULL,
	FOREIGN KEY(IDCLIENTE)
		REFERENCES CLIENTE (IDCLIENTE),
	FOREIGN KEY(IDVEICULO) 
		REFERENCES VEICULO (IDVEICULO),
	PRIMARY KEY(IDLOCACAO)
);

SELECT * FROM CLIENTE;
SELECT * FROM VEICULO;
SELECT * FROM LOCACAO;